"""Tests for the msb_ssis2sql command-line interface."""
from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from msb_ssis2sql.cli import main
from msb_ssis2sql.observability import logger


@pytest.fixture(autouse=True)
def _restore_logging():
    """main() calls configure_logging; put the silent library default back."""
    yield
    logger.remove()
    logger.disable("msb_ssis2sql")


def test_convert_writes_sql_to_stdout(example_path, capsys):
    assert main(["convert", example_path]) == 0
    out = capsys.readouterr().out
    assert "WITH [Sales_Orders_Source] AS" in out
    assert out.count("INSERT INTO") == 2


def test_convert_writes_to_output_file(example_path, tmp_path, capsys):
    target = tmp_path / "out.sql"
    assert main(["convert", example_path, "-o", str(target)]) == 0
    assert "INSERT INTO" in target.read_text(encoding="utf-8")
    captured = capsys.readouterr()
    assert captured.out == ""                       # -o diverts SQL off stdout
    assert str(target) in captured.err              # the path is reported on stderr


def test_convert_procedure_wrapping(example_path, capsys):
    assert main(["convert", example_path, "--procedure", "usp_Load"]) == 0
    assert "CREATE OR ALTER PROCEDURE usp_Load" in capsys.readouterr().out


def test_convert_no_header_omits_the_banner(example_path, capsys):
    assert main(["convert", example_path, "--no-header"]) == 0
    assert "Generated by msb_ssis2sql" not in capsys.readouterr().out


def test_convert_reports_a_warning_summary_on_stderr(example_path, capsys):
    assert main(["convert", example_path]) == 0
    assert "warning(s):" in capsys.readouterr().err


def test_convert_quiet_suppresses_the_warning_summary(example_path, capsys):
    assert main(["convert", example_path, "--quiet"]) == 0
    assert "warning(s):" not in capsys.readouterr().err


def test_convert_missing_file_returns_exit_code_2(capsys):
    assert main(["convert", "/no/such/package.dtsx"]) == 2
    assert "error" in capsys.readouterr().err


def test_inspect_prints_the_package_summary(example_path, capsys):
    assert main(["inspect", example_path]) == 0
    out = capsys.readouterr().out
    assert "Package: CustomerSalesETL" in out
    assert "data flow tasks" in out


def test_missing_subcommand_exits_nonzero():
    with pytest.raises(SystemExit):
        main([])


def test_convert_unwritable_output_path_returns_exit_code_2(example_path, tmp_path, capsys):
    # The parent directory does not exist, so write_text raises OSError.
    target = tmp_path / "missing_dir" / "out.sql"
    assert main(["convert", example_path, "-o", str(target)]) == 2
    assert "error" in capsys.readouterr().err


def test_module_entry_point_runs_main(monkeypatch):
    """`python -m msb_ssis2sql` executes __main__.py, which calls main()."""
    import runpy
    import sys

    monkeypatch.setattr(sys, "argv", ["msb_ssis2sql"])   # no subcommand -> argparse exits
    with pytest.raises(SystemExit):
        runpy.run_module("msb_ssis2sql", run_name="__main__")


# ---------------------------------------------------------------------------
# AC 7 — CLI convert-tree: exits 0 on success, exits exactly 1 on any failure.
# ---------------------------------------------------------------------------

_SALES_ETL_CLI = Path(__file__).parent.parent / "examples" / "sales_etl.dtsx"


def test_cli_convert_tree_exits_zero_on_all_success(tmp_path):
    """main(['convert-tree', input, output]) converts a tree and returns 0."""
    input_dir = tmp_path / "input"
    input_dir.mkdir()
    shutil.copy(_SALES_ETL_CLI, input_dir / "pkg.dtsx")

    rc = main(["convert-tree", str(input_dir), str(tmp_path / "output")])
    assert rc == 0
    assert (tmp_path / "output" / "pkg.sql").exists()


def test_cli_convert_tree_exits_one_when_a_package_fails(tmp_path):
    """main(['convert-tree', ...]) returns exactly 1 when the tree has a bad .dtsx."""
    input_dir = tmp_path / "input"
    input_dir.mkdir()
    (input_dir / "broken.dtsx").write_text("<not valid", encoding="utf-8")
    # Also add a valid file so we confirm isolation (converted >= 1, failed >= 1).
    shutil.copy(_SALES_ETL_CLI, input_dir / "good.dtsx")

    rc = main(["convert-tree", str(input_dir), str(tmp_path / "output")])
    assert rc == 1, f"expected exit code 1, got {rc}"
