"""Tests for the ssis2sql command-line interface."""
from __future__ import annotations

import pytest

from ssis2sql.cli import main
from ssis2sql.observability import logger


@pytest.fixture(autouse=True)
def _restore_logging():
    """main() calls configure_logging; put the silent library default back."""
    yield
    logger.remove()
    logger.disable("ssis2sql")


def test_convert_writes_sql_to_stdout(example_path, capsys):
    assert main(["convert", example_path]) == 0
    out = capsys.readouterr().out
    assert "WITH [Sales_Orders_Source] AS" in out
    assert out.count("INSERT INTO") == 2


def test_convert_writes_to_output_file(example_path, tmp_path, capsys):
    target = tmp_path / "out.sql"
    assert main(["convert", example_path, "-o", str(target)]) == 0
    assert "INSERT INTO" in target.read_text(encoding="utf-8")
    captured = capsys.readouterr()
    assert captured.out == ""                       # -o diverts SQL off stdout
    assert str(target) in captured.err              # the path is reported on stderr


def test_convert_procedure_wrapping(example_path, capsys):
    assert main(["convert", example_path, "--procedure", "usp_Load"]) == 0
    assert "CREATE OR ALTER PROCEDURE usp_Load" in capsys.readouterr().out


def test_convert_no_header_omits_the_banner(example_path, capsys):
    assert main(["convert", example_path, "--no-header"]) == 0
    assert "Generated by ssis2sql" not in capsys.readouterr().out


def test_convert_reports_a_warning_summary_on_stderr(example_path, capsys):
    assert main(["convert", example_path]) == 0
    assert "warning(s):" in capsys.readouterr().err


def test_convert_quiet_suppresses_the_warning_summary(example_path, capsys):
    assert main(["convert", example_path, "--quiet"]) == 0
    assert "warning(s):" not in capsys.readouterr().err


def test_convert_missing_file_returns_exit_code_2(capsys):
    assert main(["convert", "/no/such/package.dtsx"]) == 2
    assert "error" in capsys.readouterr().err


def test_inspect_prints_the_package_summary(example_path, capsys):
    assert main(["inspect", example_path]) == 0
    out = capsys.readouterr().out
    assert "Package: CustomerSalesETL" in out
    assert "data flow tasks" in out


def test_missing_subcommand_exits_nonzero():
    with pytest.raises(SystemExit):
        main([])
